[2025-08-31T04:49:24.269+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparking_flow.python_job scheduled__2025-08-30T12:00:00+00:00 [queued]>
[2025-08-31T04:49:24.294+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparking_flow.python_job scheduled__2025-08-30T12:00:00+00:00 [queued]>
[2025-08-31T04:49:24.297+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 1
[2025-08-31T04:49:24.332+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): python_job> on 2025-08-30 12:00:00+00:00
[2025-08-31T04:49:24.350+0000] {standard_task_runner.py:57} INFO - Started process 205 to run task
[2025-08-31T04:49:24.372+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sparking_flow', 'python_job', 'scheduled__2025-08-30T12:00:00+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/spark_***.py', '--cfg-path', '/tmp/tmp4cxi25d7']
[2025-08-31T04:49:24.380+0000] {standard_task_runner.py:85} INFO - Job 99: Subtask python_job
[2025-08-31T04:49:24.949+0000] {task_command.py:415} INFO - Running <TaskInstance: sparking_flow.python_job scheduled__2025-08-30T12:00:00+00:00 [running]> on host 81b7fe425a18
[2025-08-31T04:49:25.402+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Kudzaishe Manyanya' AIRFLOW_CTX_DAG_ID='sparking_flow' AIRFLOW_CTX_TASK_ID='python_job' AIRFLOW_CTX_EXECUTION_DATE='2025-08-30T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-30T12:00:00+00:00'
[2025-08-31T04:49:25.455+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2025-08-31T04:49:25.463+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --jars /opt/spark/external-jars/apache-spark-sql-connector.jar --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py
[2025-08-31T04:49:27.479+0000] {spark_submit.py:579} INFO - WARNING: Using incubator modules: jdk.incubator.vector
[2025-08-31T04:49:39.855+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:39 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-08-31T04:49:58.741+0000] {spark_submit.py:579} INFO - Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
[2025-08-31T04:49:58.838+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:58 INFO SparkContext: Running Spark version 4.0.0
[2025-08-31T04:49:58.843+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:58 INFO SparkContext: OS info Linux, 6.6.87.2-microsoft-standard-WSL2, amd64
[2025-08-31T04:49:58.850+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:58 INFO SparkContext: Java version 17.0.15
[2025-08-31T04:49:59.315+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:59 INFO ResourceUtils: ==============================================================
[2025-08-31T04:49:59.319+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:59 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-08-31T04:49:59.322+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:59 INFO ResourceUtils: ==============================================================
[2025-08-31T04:49:59.323+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:59 INFO SparkContext: Submitted application: PythonWordCount
[2025-08-31T04:49:59.517+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:59 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-08-31T04:49:59.540+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:59 INFO ResourceProfile: Limiting resource is cpu
[2025-08-31T04:49:59.568+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:59 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-08-31T04:50:00.441+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:00 INFO SecurityManager: Changing view acls to: ***
[2025-08-31T04:50:00.560+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:00 INFO SecurityManager: Changing modify acls to: ***
[2025-08-31T04:50:00.565+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:00 INFO SecurityManager: Changing view acls groups to: ***
[2025-08-31T04:50:00.575+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:00 INFO SecurityManager: Changing modify acls groups to: ***
[2025-08-31T04:50:00.612+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:00 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: *** groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY; RPC SSL disabled
[2025-08-31T04:50:04.541+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:04 INFO Utils: Successfully started service 'sparkDriver' on port 33289.
[2025-08-31T04:50:04.705+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:04 INFO SparkEnv: Registering MapOutputTracker
[2025-08-31T04:50:04.768+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:04 INFO SparkEnv: Registering BlockManagerMaster
[2025-08-31T04:50:04.835+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:04 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-08-31T04:50:04.850+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:04 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-08-31T04:50:04.860+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:04 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-08-31T04:50:06.524+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:06 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-a51e2d66-a81d-49b7-9dc1-3521f950a12a
[2025-08-31T04:50:06.594+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:06 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-08-31T04:50:07.303+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:07 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-08-31T04:50:07.918+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:07 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-08-31T04:50:07.931+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:07 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2025-08-31T04:50:07.933+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:07 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2025-08-31T04:50:07.933+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:07 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2025-08-31T04:50:08.023+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:08 INFO Utils: Successfully started service 'SparkUI' on port 4044.
[2025-08-31T04:50:08.254+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:08 INFO SparkContext: Added JAR file:///opt/spark/external-jars/apache-spark-sql-connector.jar at spark://81b7fe425a18:33289/jars/apache-spark-sql-connector.jar with timestamp 1756615798268
[2025-08-31T04:50:08.296+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:08 INFO SecurityManager: Changing view acls to: ***
[2025-08-31T04:50:08.298+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:08 INFO SecurityManager: Changing modify acls to: ***
[2025-08-31T04:50:08.307+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:08 INFO SecurityManager: Changing view acls groups to: ***
[2025-08-31T04:50:08.308+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:08 INFO SecurityManager: Changing modify acls groups to: ***
[2025-08-31T04:50:08.310+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:08 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: *** groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY; RPC SSL disabled
[2025-08-31T04:50:09.439+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:09 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-08-31T04:50:09.744+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:09 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.2:7077 after 155 ms (0 ms spent in bootstraps)
[2025-08-31T04:50:11.589+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:11 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250831045011-0009
[2025-08-31T04:50:11.660+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:11 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 46813.
[2025-08-31T04:50:11.663+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:11 INFO NettyBlockTransferService: Server created on 81b7fe425a18:46813
[2025-08-31T04:50:11.682+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:11 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-08-31T04:50:11.768+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:11 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 81b7fe425a18, 46813, None)
[2025-08-31T04:50:11.812+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:11 INFO BlockManagerMasterEndpoint: Registering block manager 81b7fe425a18:46813 with 434.4 MiB RAM, BlockManagerId(driver, 81b7fe425a18, 46813, None)
[2025-08-31T04:50:11.823+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:11 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 81b7fe425a18, 46813, None)
[2025-08-31T04:50:11.835+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:11 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 81b7fe425a18, 46813, None)
[2025-08-31T04:50:13.222+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:13 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-08-31T04:50:25.057+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/jobs/job.py", line 190, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
