[2025-08-18T08:00:03.671+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparking_flow.python_job scheduled__2025-08-18T06:00:00+00:00 [queued]>
[2025-08-18T08:00:03.682+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparking_flow.python_job scheduled__2025-08-18T06:00:00+00:00 [queued]>
[2025-08-18T08:00:03.683+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-08-18T08:00:03.696+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): python_job> on 2025-08-18 06:00:00+00:00
[2025-08-18T08:00:03.700+0000] {standard_task_runner.py:57} INFO - Started process 2887 to run task
[2025-08-18T08:00:03.703+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sparking_flow', 'python_job', 'scheduled__2025-08-18T06:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/spark_***.py', '--cfg-path', '/tmp/tmpfk2g00_q']
[2025-08-18T08:00:03.705+0000] {standard_task_runner.py:85} INFO - Job 43: Subtask python_job
[2025-08-18T08:00:03.765+0000] {task_command.py:415} INFO - Running <TaskInstance: sparking_flow.python_job scheduled__2025-08-18T06:00:00+00:00 [running]> on host 81b7fe425a18
[2025-08-18T08:00:03.861+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Kudzaishe Manyanya' AIRFLOW_CTX_DAG_ID='sparking_flow' AIRFLOW_CTX_TASK_ID='python_job' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-18T06:00:00+00:00'
[2025-08-18T08:00:03.882+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2025-08-18T08:00:03.886+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --jars /opt/spark/external-jars/apache-spark-sql-connector.jar --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py
[2025-08-18T08:00:04.294+0000] {spark_submit.py:579} INFO - WARNING: Using incubator modules: jdk.incubator.vector
[2025-08-18T08:00:05.655+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:05 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-08-18T08:00:07.676+0000] {spark_submit.py:579} INFO - Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
[2025-08-18T08:00:07.680+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:07 INFO SparkContext: Running Spark version 4.0.0
[2025-08-18T08:00:07.681+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:07 INFO SparkContext: OS info Linux, 6.6.87.2-microsoft-standard-WSL2, amd64
[2025-08-18T08:00:07.682+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:07 INFO SparkContext: Java version 17.0.15
[2025-08-18T08:00:07.699+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:07 INFO ResourceUtils: ==============================================================
[2025-08-18T08:00:07.700+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:07 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-08-18T08:00:07.700+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:07 INFO ResourceUtils: ==============================================================
[2025-08-18T08:00:07.701+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:07 INFO SparkContext: Submitted application: PythonWordCount
[2025-08-18T08:00:07.718+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:07 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-08-18T08:00:07.720+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:07 INFO ResourceProfile: Limiting resource is cpu
[2025-08-18T08:00:07.721+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:07 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-08-18T08:00:07.756+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:07 INFO SecurityManager: Changing view acls to: ***
[2025-08-18T08:00:07.757+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:07 INFO SecurityManager: Changing modify acls to: ***
[2025-08-18T08:00:07.757+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:07 INFO SecurityManager: Changing view acls groups to: ***
[2025-08-18T08:00:07.758+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:07 INFO SecurityManager: Changing modify acls groups to: ***
[2025-08-18T08:00:07.759+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:07 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: *** groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY; RPC SSL disabled
[2025-08-18T08:00:07.953+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:07 INFO Utils: Successfully started service 'sparkDriver' on port 37611.
[2025-08-18T08:00:07.976+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:07 INFO SparkEnv: Registering MapOutputTracker
[2025-08-18T08:00:07.986+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:07 INFO SparkEnv: Registering BlockManagerMaster
[2025-08-18T08:00:08.000+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:07 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-08-18T08:00:08.000+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:08 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-08-18T08:00:08.002+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:08 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-08-18T08:00:08.023+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:08 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-74764dbc-d892-49c0-8fc3-ccefbe7fb198
[2025-08-18T08:00:08.041+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:08 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-08-18T08:00:08.159+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:08 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-08-18T08:00:08.225+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:08 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-08-18T08:00:08.271+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:08 INFO SparkContext: Added JAR file:///opt/spark/external-jars/apache-spark-sql-connector.jar at spark://81b7fe425a18:37611/jars/apache-spark-sql-connector.jar with timestamp 1755504007670
[2025-08-18T08:00:08.303+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:08 INFO SecurityManager: Changing view acls to: ***
[2025-08-18T08:00:08.304+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:08 INFO SecurityManager: Changing modify acls to: ***
[2025-08-18T08:00:08.305+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:08 INFO SecurityManager: Changing view acls groups to: ***
[2025-08-18T08:00:08.305+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:08 INFO SecurityManager: Changing modify acls groups to: ***
[2025-08-18T08:00:08.306+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:08 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: *** groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY; RPC SSL disabled
[2025-08-18T08:00:08.445+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:08 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-08-18T08:00:08.481+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:08 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.3:7077 after 18 ms (0 ms spent in bootstraps)
[2025-08-18T08:00:08.595+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:08 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250818080008-0002
[2025-08-18T08:00:08.599+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:08 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250818080008-0002/0 on worker-20250818041359-172.18.0.5-40851 (172.18.0.5:40851) with 2 core(s)
[2025-08-18T08:00:08.603+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:08 INFO StandaloneSchedulerBackend: Granted executor ID app-20250818080008-0002/0 on hostPort 172.18.0.5:40851 with 2 core(s), 1024.0 MiB RAM
[2025-08-18T08:00:08.609+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:08 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 40319.
[2025-08-18T08:00:08.610+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:08 INFO NettyBlockTransferService: Server created on 81b7fe425a18:40319
[2025-08-18T08:00:08.613+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:08 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-08-18T08:00:08.628+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:08 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 81b7fe425a18, 40319, None)
[2025-08-18T08:00:08.633+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:08 INFO BlockManagerMasterEndpoint: Registering block manager 81b7fe425a18:40319 with 434.4 MiB RAM, BlockManagerId(driver, 81b7fe425a18, 40319, None)
[2025-08-18T08:00:08.635+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:08 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 81b7fe425a18, 40319, None)
[2025-08-18T08:00:08.636+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:08 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 81b7fe425a18, 40319, None)
[2025-08-18T08:00:08.697+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:08 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250818080008-0002/0 is now RUNNING
[2025-08-18T08:00:08.769+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:08 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-08-18T08:00:11.534+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2025-08-18T08:00:11.537+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
[2025-08-18T08:00:11.538+0000] {spark_submit.py:579} INFO - conn = connection.create_connection(
[2025-08-18T08:00:11.538+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
[2025-08-18T08:00:11.539+0000] {spark_submit.py:579} INFO - for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
[2025-08-18T08:00:11.539+0000] {spark_submit.py:579} INFO - File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
[2025-08-18T08:00:11.539+0000] {spark_submit.py:579} INFO - for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
[2025-08-18T08:00:11.539+0000] {spark_submit.py:579} INFO - socket.gaierror: [Errno -2] Name or service not known
[2025-08-18T08:00:11.540+0000] {spark_submit.py:579} INFO - 
[2025-08-18T08:00:11.540+0000] {spark_submit.py:579} INFO - During handling of the above exception, another exception occurred:
[2025-08-18T08:00:11.540+0000] {spark_submit.py:579} INFO - 
[2025-08-18T08:00:11.541+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2025-08-18T08:00:11.541+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
[2025-08-18T08:00:11.541+0000] {spark_submit.py:579} INFO - httplib_response = self._make_request(
[2025-08-18T08:00:11.542+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 403, in _make_request
[2025-08-18T08:00:11.542+0000] {spark_submit.py:579} INFO - self._validate_conn(conn)
[2025-08-18T08:00:11.542+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
[2025-08-18T08:00:11.542+0000] {spark_submit.py:579} INFO - conn.connect()
[2025-08-18T08:00:11.543+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
[2025-08-18T08:00:11.543+0000] {spark_submit.py:579} INFO - self.sock = conn = self._new_conn()
[2025-08-18T08:00:11.543+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
[2025-08-18T08:00:11.544+0000] {spark_submit.py:579} INFO - raise NewConnectionError(
[2025-08-18T08:00:11.544+0000] {spark_submit.py:579} INFO - urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x78db550406d0>: Failed to establish a new connection: [Errno -2] Name or service not known
[2025-08-18T08:00:11.544+0000] {spark_submit.py:579} INFO - 
[2025-08-18T08:00:11.544+0000] {spark_submit.py:579} INFO - During handling of the above exception, another exception occurred:
[2025-08-18T08:00:11.545+0000] {spark_submit.py:579} INFO - 
[2025-08-18T08:00:11.545+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2025-08-18T08:00:11.545+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
[2025-08-18T08:00:11.545+0000] {spark_submit.py:579} INFO - resp = conn.urlopen(
[2025-08-18T08:00:11.545+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
[2025-08-18T08:00:11.546+0000] {spark_submit.py:579} INFO - retries = retries.increment(
[2025-08-18T08:00:11.546+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
[2025-08-18T08:00:11.546+0000] {spark_submit.py:579} INFO - raise MaxRetryError(_pool, url, error or ResponseError(cause))
[2025-08-18T08:00:11.546+0000] {spark_submit.py:579} INFO - urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.chess.com', port=443): Max retries exceeded with url: /pub/leaderboards (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x78db550406d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-08-18T08:00:11.547+0000] {spark_submit.py:579} INFO - 
[2025-08-18T08:00:11.547+0000] {spark_submit.py:579} INFO - During handling of the above exception, another exception occurred:
[2025-08-18T08:00:11.547+0000] {spark_submit.py:579} INFO - 
[2025-08-18T08:00:11.548+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2025-08-18T08:00:11.548+0000] {spark_submit.py:579} INFO - File "/opt/***/jobs/python/wordcountjob.py", line 32, in <module>
[2025-08-18T08:00:11.548+0000] {spark_submit.py:579} INFO - response = requests.get(url, headers=headers)
[2025-08-18T08:00:11.549+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/api.py", line 73, in get
[2025-08-18T08:00:11.549+0000] {spark_submit.py:579} INFO - return request("get", url, params=params, **kwargs)
[2025-08-18T08:00:11.549+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
[2025-08-18T08:00:11.550+0000] {spark_submit.py:579} INFO - return session.request(method=method, url=url, **kwargs)
[2025-08-18T08:00:11.550+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
[2025-08-18T08:00:11.550+0000] {spark_submit.py:579} INFO - resp = self.send(prep, **send_kwargs)
[2025-08-18T08:00:11.551+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
[2025-08-18T08:00:11.551+0000] {spark_submit.py:579} INFO - r = adapter.send(request, **kwargs)
[2025-08-18T08:00:11.551+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
[2025-08-18T08:00:11.552+0000] {spark_submit.py:579} INFO - raise ConnectionError(e, request=request)
[2025-08-18T08:00:11.552+0000] {spark_submit.py:579} INFO - requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.chess.com', port=443): Max retries exceeded with url: /pub/leaderboards (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x78db550406d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-08-18T08:00:11.727+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:11 INFO SparkContext: Invoking stop() from shutdown hook
[2025-08-18T08:00:11.729+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:11 INFO SparkContext: SparkContext is stopping with exitCode 0 from run at Executors.java:539.
[2025-08-18T08:00:11.738+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:11 INFO SparkUI: Stopped Spark web UI at http://81b7fe425a18:4040
[2025-08-18T08:00:11.741+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:11 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-08-18T08:00:11.742+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:11 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2025-08-18T08:00:11.755+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:11 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-08-18T08:00:11.784+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:11 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-08-18T08:00:11.785+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:11 INFO MemoryStore: MemoryStore cleared
[2025-08-18T08:00:11.786+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:11 INFO BlockManager: BlockManager stopped
[2025-08-18T08:00:11.793+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:11 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-08-18T08:00:11.796+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:11 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-08-18T08:00:11.821+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:11 INFO SparkContext: Successfully stopped SparkContext
[2025-08-18T08:00:11.822+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:11 INFO ShutdownHookManager: Shutdown hook called
[2025-08-18T08:00:11.822+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:11 INFO ShutdownHookManager: Deleting directory /tmp/spark-29ad7416-de94-48f9-b7fe-9adfebeedd13/pyspark-a4752c33-c3a6-4344-90cb-9400877cfb09
[2025-08-18T08:00:11.838+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:11 INFO ShutdownHookManager: Deleting directory /tmp/spark-01a1cef6-a756-4819-abed-e2f29e3487c3
[2025-08-18T08:00:11.852+0000] {spark_submit.py:579} INFO - 25/08/18 08:00:11 INFO ShutdownHookManager: Deleting directory /tmp/spark-29ad7416-de94-48f9-b7fe-9adfebeedd13
[2025-08-18T08:00:11.943+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --jars /opt/spark/external-jars/apache-spark-sql-connector.jar --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py. Error code is: 1.
[2025-08-18T08:00:11.958+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=sparking_flow, task_id=python_job, execution_date=20250818T060000, start_date=20250818T080003, end_date=20250818T080011
[2025-08-18T08:00:11.981+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 43 for task python_job (Cannot execute: spark-submit --master spark://spark-master:7077 --jars /opt/spark/external-jars/apache-spark-sql-connector.jar --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py. Error code is: 1.; 2887)
[2025-08-18T08:00:12.030+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-08-18T08:00:12.085+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
