[2025-08-31T04:49:24.205+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparking_flow.python_job scheduled__2025-08-30T16:00:00+00:00 [queued]>
[2025-08-31T04:49:24.229+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparking_flow.python_job scheduled__2025-08-30T16:00:00+00:00 [queued]>
[2025-08-31T04:49:24.230+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 1
[2025-08-31T04:49:24.288+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): python_job> on 2025-08-30 16:00:00+00:00
[2025-08-31T04:49:24.307+0000] {standard_task_runner.py:57} INFO - Started process 202 to run task
[2025-08-31T04:49:24.313+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sparking_flow', 'python_job', 'scheduled__2025-08-30T16:00:00+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/spark_***.py', '--cfg-path', '/tmp/tmp23ps1vk4']
[2025-08-31T04:49:24.320+0000] {standard_task_runner.py:85} INFO - Job 95: Subtask python_job
[2025-08-31T04:49:24.557+0000] {task_command.py:415} INFO - Running <TaskInstance: sparking_flow.python_job scheduled__2025-08-30T16:00:00+00:00 [running]> on host 81b7fe425a18
[2025-08-31T04:49:25.062+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Kudzaishe Manyanya' AIRFLOW_CTX_DAG_ID='sparking_flow' AIRFLOW_CTX_TASK_ID='python_job' AIRFLOW_CTX_EXECUTION_DATE='2025-08-30T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-30T16:00:00+00:00'
[2025-08-31T04:49:25.130+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2025-08-31T04:49:25.134+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --jars /opt/spark/external-jars/apache-spark-sql-connector.jar --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py
[2025-08-31T04:49:27.497+0000] {spark_submit.py:579} INFO - WARNING: Using incubator modules: jdk.incubator.vector
[2025-08-31T04:49:42.037+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:41 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-08-31T04:49:58.496+0000] {spark_submit.py:579} INFO - Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
[2025-08-31T04:49:58.539+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:58 INFO SparkContext: Running Spark version 4.0.0
[2025-08-31T04:49:58.557+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:58 INFO SparkContext: OS info Linux, 6.6.87.2-microsoft-standard-WSL2, amd64
[2025-08-31T04:49:58.564+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:58 INFO SparkContext: Java version 17.0.15
[2025-08-31T04:49:58.811+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:58 INFO ResourceUtils: ==============================================================
[2025-08-31T04:49:58.815+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:58 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-08-31T04:49:58.817+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:58 INFO ResourceUtils: ==============================================================
[2025-08-31T04:49:58.835+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:58 INFO SparkContext: Submitted application: PythonWordCount
[2025-08-31T04:49:59.013+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:59 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-08-31T04:49:59.024+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:59 INFO ResourceProfile: Limiting resource is cpu
[2025-08-31T04:49:59.030+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:59 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-08-31T04:49:59.613+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:59 INFO SecurityManager: Changing view acls to: ***
[2025-08-31T04:49:59.640+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:59 INFO SecurityManager: Changing modify acls to: ***
[2025-08-31T04:49:59.646+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:59 INFO SecurityManager: Changing view acls groups to: ***
[2025-08-31T04:49:59.655+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:59 INFO SecurityManager: Changing modify acls groups to: ***
[2025-08-31T04:49:59.662+0000] {spark_submit.py:579} INFO - 25/08/31 04:49:59 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: *** groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY; RPC SSL disabled
[2025-08-31T04:50:04.603+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:04 INFO Utils: Successfully started service 'sparkDriver' on port 46079.
[2025-08-31T04:50:04.794+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:04 INFO SparkEnv: Registering MapOutputTracker
[2025-08-31T04:50:04.874+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:04 INFO SparkEnv: Registering BlockManagerMaster
[2025-08-31T04:50:04.920+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:04 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-08-31T04:50:04.922+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:04 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-08-31T04:50:04.933+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:04 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-08-31T04:50:06.521+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:06 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-e9184566-da03-42e6-93cf-99c964d7ff82
[2025-08-31T04:50:06.671+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:06 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-08-31T04:50:07.557+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:07 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-08-31T04:50:08.039+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:08 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-08-31T04:50:08.050+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:08 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2025-08-31T04:50:08.051+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:08 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2025-08-31T04:50:08.061+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:08 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2025-08-31T04:50:08.063+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:08 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
[2025-08-31T04:50:08.064+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:08 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
[2025-08-31T04:50:08.065+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:08 WARN Utils: Service 'SparkUI' could not bind on port 4046. Attempting port 4047.
[2025-08-31T04:50:08.070+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:08 WARN Utils: Service 'SparkUI' could not bind on port 4047. Attempting port 4048.
[2025-08-31T04:50:08.074+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:08 WARN Utils: Service 'SparkUI' could not bind on port 4048. Attempting port 4049.
[2025-08-31T04:50:08.107+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:08 INFO Utils: Successfully started service 'SparkUI' on port 4049.
[2025-08-31T04:50:08.427+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:08 INFO SparkContext: Added JAR file:///opt/spark/external-jars/apache-spark-sql-connector.jar at spark://81b7fe425a18:46079/jars/apache-spark-sql-connector.jar with timestamp 1756615798198
[2025-08-31T04:50:08.548+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:08 INFO SecurityManager: Changing view acls to: ***
[2025-08-31T04:50:08.549+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:08 INFO SecurityManager: Changing modify acls to: ***
[2025-08-31T04:50:08.557+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:08 INFO SecurityManager: Changing view acls groups to: ***
[2025-08-31T04:50:08.559+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:08 INFO SecurityManager: Changing modify acls groups to: ***
[2025-08-31T04:50:08.576+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:08 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: *** groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY; RPC SSL disabled
[2025-08-31T04:50:09.706+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:09 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-08-31T04:50:09.917+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:09 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.2:7077 after 135 ms (0 ms spent in bootstraps)
[2025-08-31T04:50:11.659+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:11 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250831045011-0012
[2025-08-31T04:50:11.760+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:11 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 35727.
[2025-08-31T04:50:11.764+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:11 INFO NettyBlockTransferService: Server created on 81b7fe425a18:35727
[2025-08-31T04:50:11.770+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:11 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-08-31T04:50:11.854+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:11 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 81b7fe425a18, 35727, None)
[2025-08-31T04:50:11.906+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:11 INFO BlockManagerMasterEndpoint: Registering block manager 81b7fe425a18:35727 with 434.4 MiB RAM, BlockManagerId(driver, 81b7fe425a18, 35727, None)
[2025-08-31T04:50:11.922+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:11 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 81b7fe425a18, 35727, None)
[2025-08-31T04:50:11.924+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:11 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 81b7fe425a18, 35727, None)
[2025-08-31T04:50:12.913+0000] {spark_submit.py:579} INFO - 25/08/31 04:50:12 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-08-31T04:50:24.822+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/jobs/job.py", line 190, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
