[2025-08-18T15:36:55.360+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparking_flow.python_job manual__2025-08-18T15:36:50.839461+00:00 [queued]>
[2025-08-18T15:36:55.369+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparking_flow.python_job manual__2025-08-18T15:36:50.839461+00:00 [queued]>
[2025-08-18T15:36:55.370+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-08-18T15:36:55.385+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): python_job> on 2025-08-18 15:36:50.839461+00:00
[2025-08-18T15:36:55.391+0000] {standard_task_runner.py:57} INFO - Started process 8119 to run task
[2025-08-18T15:36:55.394+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sparking_flow', 'python_job', 'manual__2025-08-18T15:36:50.839461+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/spark_***.py', '--cfg-path', '/tmp/tmpsummvfjt']
[2025-08-18T15:36:55.397+0000] {standard_task_runner.py:85} INFO - Job 51: Subtask python_job
[2025-08-18T15:36:55.464+0000] {task_command.py:415} INFO - Running <TaskInstance: sparking_flow.python_job manual__2025-08-18T15:36:50.839461+00:00 [running]> on host 81b7fe425a18
[2025-08-18T15:36:55.550+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Kudzaishe Manyanya' AIRFLOW_CTX_DAG_ID='sparking_flow' AIRFLOW_CTX_TASK_ID='python_job' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T15:36:50.839461+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T15:36:50.839461+00:00'
[2025-08-18T15:36:55.563+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2025-08-18T15:36:55.564+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --jars /opt/spark/external-jars/apache-spark-sql-connector.jar --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py
[2025-08-18T15:36:56.297+0000] {spark_submit.py:579} INFO - WARNING: Using incubator modules: jdk.incubator.vector
[2025-08-18T15:36:57.677+0000] {spark_submit.py:579} INFO - 25/08/18 15:36:57 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-08-18T15:37:00.144+0000] {spark_submit.py:579} INFO - Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
[2025-08-18T15:37:00.150+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:00 INFO SparkContext: Running Spark version 4.0.0
[2025-08-18T15:37:00.153+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:00 INFO SparkContext: OS info Linux, 6.6.87.2-microsoft-standard-WSL2, amd64
[2025-08-18T15:37:00.154+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:00 INFO SparkContext: Java version 17.0.15
[2025-08-18T15:37:00.182+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:00 INFO ResourceUtils: ==============================================================
[2025-08-18T15:37:00.183+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:00 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-08-18T15:37:00.184+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:00 INFO ResourceUtils: ==============================================================
[2025-08-18T15:37:00.184+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:00 INFO SparkContext: Submitted application: PythonWordCount
[2025-08-18T15:37:00.212+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:00 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-08-18T15:37:00.215+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:00 INFO ResourceProfile: Limiting resource is cpu
[2025-08-18T15:37:00.216+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:00 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-08-18T15:37:00.259+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:00 INFO SecurityManager: Changing view acls to: ***
[2025-08-18T15:37:00.260+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:00 INFO SecurityManager: Changing modify acls to: ***
[2025-08-18T15:37:00.260+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:00 INFO SecurityManager: Changing view acls groups to: ***
[2025-08-18T15:37:00.261+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:00 INFO SecurityManager: Changing modify acls groups to: ***
[2025-08-18T15:37:00.262+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:00 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: *** groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY; RPC SSL disabled
[2025-08-18T15:37:00.589+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:00 INFO Utils: Successfully started service 'sparkDriver' on port 45207.
[2025-08-18T15:37:00.652+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:00 INFO SparkEnv: Registering MapOutputTracker
[2025-08-18T15:37:00.667+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:00 INFO SparkEnv: Registering BlockManagerMaster
[2025-08-18T15:37:00.685+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:00 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-08-18T15:37:00.686+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:00 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-08-18T15:37:00.691+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:00 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-08-18T15:37:00.718+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:00 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-ea217bc3-049e-46c1-94fd-c8cecab0a3df
[2025-08-18T15:37:00.742+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:00 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-08-18T15:37:00.869+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:00 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-08-18T15:37:00.948+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:00 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-08-18T15:37:00.991+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:00 INFO SparkContext: Added JAR file:///opt/spark/external-jars/apache-spark-sql-connector.jar at spark://81b7fe425a18:45207/jars/apache-spark-sql-connector.jar with timestamp 1755531420134
[2025-08-18T15:37:01.012+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:01 INFO SecurityManager: Changing view acls to: ***
[2025-08-18T15:37:01.012+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:01 INFO SecurityManager: Changing modify acls to: ***
[2025-08-18T15:37:01.016+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:01 INFO SecurityManager: Changing view acls groups to: ***
[2025-08-18T15:37:01.016+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:01 INFO SecurityManager: Changing modify acls groups to: ***
[2025-08-18T15:37:01.017+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:01 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: *** groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY; RPC SSL disabled
[2025-08-18T15:37:01.133+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:01 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-08-18T15:37:01.174+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:01 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.3:7077 after 20 ms (0 ms spent in bootstraps)
[2025-08-18T15:37:01.306+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:01 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250818153701-0006
[2025-08-18T15:37:01.314+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:01 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 37271.
[2025-08-18T15:37:01.315+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:01 INFO NettyBlockTransferService: Server created on 81b7fe425a18:37271
[2025-08-18T15:37:01.316+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:01 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-08-18T15:37:01.323+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:01 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250818153701-0006/0 on worker-20250818041359-172.18.0.5-40851 (172.18.0.5:40851) with 2 core(s)
[2025-08-18T15:37:01.325+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:01 INFO StandaloneSchedulerBackend: Granted executor ID app-20250818153701-0006/0 on hostPort 172.18.0.5:40851 with 2 core(s), 1024.0 MiB RAM
[2025-08-18T15:37:01.331+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:01 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 81b7fe425a18, 37271, None)
[2025-08-18T15:37:01.335+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:01 INFO BlockManagerMasterEndpoint: Registering block manager 81b7fe425a18:37271 with 434.4 MiB RAM, BlockManagerId(driver, 81b7fe425a18, 37271, None)
[2025-08-18T15:37:01.337+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:01 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 81b7fe425a18, 37271, None)
[2025-08-18T15:37:01.338+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:01 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 81b7fe425a18, 37271, None)
[2025-08-18T15:37:01.449+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:01 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-08-18T15:37:01.579+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:01 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250818153701-0006/0 is now RUNNING
[2025-08-18T15:37:04.458+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2025-08-18T15:37:04.458+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
[2025-08-18T15:37:04.458+0000] {spark_submit.py:579} INFO - conn = connection.create_connection(
[2025-08-18T15:37:04.459+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
[2025-08-18T15:37:04.459+0000] {spark_submit.py:579} INFO - for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
[2025-08-18T15:37:04.459+0000] {spark_submit.py:579} INFO - File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
[2025-08-18T15:37:04.459+0000] {spark_submit.py:579} INFO - for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
[2025-08-18T15:37:04.460+0000] {spark_submit.py:579} INFO - socket.gaierror: [Errno -2] Name or service not known
[2025-08-18T15:37:04.460+0000] {spark_submit.py:579} INFO - 
[2025-08-18T15:37:04.460+0000] {spark_submit.py:579} INFO - During handling of the above exception, another exception occurred:
[2025-08-18T15:37:04.460+0000] {spark_submit.py:579} INFO - 
[2025-08-18T15:37:04.461+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2025-08-18T15:37:04.461+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
[2025-08-18T15:37:04.461+0000] {spark_submit.py:579} INFO - httplib_response = self._make_request(
[2025-08-18T15:37:04.461+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 403, in _make_request
[2025-08-18T15:37:04.462+0000] {spark_submit.py:579} INFO - self._validate_conn(conn)
[2025-08-18T15:37:04.462+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
[2025-08-18T15:37:04.462+0000] {spark_submit.py:579} INFO - conn.connect()
[2025-08-18T15:37:04.462+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
[2025-08-18T15:37:04.463+0000] {spark_submit.py:579} INFO - self.sock = conn = self._new_conn()
[2025-08-18T15:37:04.463+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
[2025-08-18T15:37:04.463+0000] {spark_submit.py:579} INFO - raise NewConnectionError(
[2025-08-18T15:37:04.464+0000] {spark_submit.py:579} INFO - urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x70afd3f6c6d0>: Failed to establish a new connection: [Errno -2] Name or service not known
[2025-08-18T15:37:04.464+0000] {spark_submit.py:579} INFO - 
[2025-08-18T15:37:04.464+0000] {spark_submit.py:579} INFO - During handling of the above exception, another exception occurred:
[2025-08-18T15:37:04.465+0000] {spark_submit.py:579} INFO - 
[2025-08-18T15:37:04.465+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2025-08-18T15:37:04.465+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
[2025-08-18T15:37:04.466+0000] {spark_submit.py:579} INFO - resp = conn.urlopen(
[2025-08-18T15:37:04.466+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
[2025-08-18T15:37:04.466+0000] {spark_submit.py:579} INFO - retries = retries.increment(
[2025-08-18T15:37:04.466+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
[2025-08-18T15:37:04.467+0000] {spark_submit.py:579} INFO - raise MaxRetryError(_pool, url, error or ResponseError(cause))
[2025-08-18T15:37:04.467+0000] {spark_submit.py:579} INFO - urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.chess.com', port=443): Max retries exceeded with url: /pub/leaderboards (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x70afd3f6c6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-08-18T15:37:04.467+0000] {spark_submit.py:579} INFO - 
[2025-08-18T15:37:04.467+0000] {spark_submit.py:579} INFO - During handling of the above exception, another exception occurred:
[2025-08-18T15:37:04.468+0000] {spark_submit.py:579} INFO - 
[2025-08-18T15:37:04.468+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2025-08-18T15:37:04.468+0000] {spark_submit.py:579} INFO - File "/opt/***/jobs/python/wordcountjob.py", line 32, in <module>
[2025-08-18T15:37:04.468+0000] {spark_submit.py:579} INFO - response = requests.get(url, headers=headers)
[2025-08-18T15:37:04.469+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/api.py", line 73, in get
[2025-08-18T15:37:04.469+0000] {spark_submit.py:579} INFO - return request("get", url, params=params, **kwargs)
[2025-08-18T15:37:04.470+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
[2025-08-18T15:37:04.470+0000] {spark_submit.py:579} INFO - return session.request(method=method, url=url, **kwargs)
[2025-08-18T15:37:04.470+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
[2025-08-18T15:37:04.471+0000] {spark_submit.py:579} INFO - resp = self.send(prep, **send_kwargs)
[2025-08-18T15:37:04.471+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
[2025-08-18T15:37:04.471+0000] {spark_submit.py:579} INFO - r = adapter.send(request, **kwargs)
[2025-08-18T15:37:04.471+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
[2025-08-18T15:37:04.472+0000] {spark_submit.py:579} INFO - raise ConnectionError(e, request=request)
[2025-08-18T15:37:04.472+0000] {spark_submit.py:579} INFO - requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.chess.com', port=443): Max retries exceeded with url: /pub/leaderboards (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x70afd3f6c6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-08-18T15:37:04.650+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:04 INFO SparkContext: Invoking stop() from shutdown hook
[2025-08-18T15:37:04.654+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:04 INFO SparkContext: SparkContext is stopping with exitCode 0 from run at Executors.java:539.
[2025-08-18T15:37:04.665+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:04 INFO SparkUI: Stopped Spark web UI at http://81b7fe425a18:4040
[2025-08-18T15:37:04.669+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:04 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-08-18T15:37:04.673+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:04 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2025-08-18T15:37:04.686+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:04 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-08-18T15:37:04.714+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:04 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-08-18T15:37:04.714+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:04 INFO MemoryStore: MemoryStore cleared
[2025-08-18T15:37:04.715+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:04 INFO BlockManager: BlockManager stopped
[2025-08-18T15:37:04.721+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:04 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-08-18T15:37:04.723+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:04 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-08-18T15:37:04.745+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:04 INFO SparkContext: Successfully stopped SparkContext
[2025-08-18T15:37:04.746+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:04 INFO ShutdownHookManager: Shutdown hook called
[2025-08-18T15:37:04.747+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:04 INFO ShutdownHookManager: Deleting directory /tmp/spark-5b53b3f4-dc58-4da8-8c9c-dd6238b4b42c/pyspark-40382699-11eb-410e-b0dd-a392dfd98b5c
[2025-08-18T15:37:04.760+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:04 INFO ShutdownHookManager: Deleting directory /tmp/spark-5b53b3f4-dc58-4da8-8c9c-dd6238b4b42c
[2025-08-18T15:37:04.773+0000] {spark_submit.py:579} INFO - 25/08/18 15:37:04 INFO ShutdownHookManager: Deleting directory /tmp/spark-c8bf51d6-93c2-4081-8933-0b00f015c4be
[2025-08-18T15:37:04.827+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --jars /opt/spark/external-jars/apache-spark-sql-connector.jar --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py. Error code is: 1.
[2025-08-18T15:37:04.831+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=sparking_flow, task_id=python_job, execution_date=20250818T153650, start_date=20250818T153655, end_date=20250818T153704
[2025-08-18T15:37:04.845+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 51 for task python_job (Cannot execute: spark-submit --master spark://spark-master:7077 --jars /opt/spark/external-jars/apache-spark-sql-connector.jar --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py. Error code is: 1.; 8119)
[2025-08-18T15:37:04.852+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-08-18T15:37:04.872+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
