[2025-08-18T15:39:54.008+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparking_flow.python_job manual__2025-08-18T15:39:50.543307+00:00 [queued]>
[2025-08-18T15:39:54.016+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparking_flow.python_job manual__2025-08-18T15:39:50.543307+00:00 [queued]>
[2025-08-18T15:39:54.017+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-08-18T15:39:54.030+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): python_job> on 2025-08-18 15:39:50.543307+00:00
[2025-08-18T15:39:54.037+0000] {standard_task_runner.py:57} INFO - Started process 8326 to run task
[2025-08-18T15:39:54.041+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sparking_flow', 'python_job', 'manual__2025-08-18T15:39:50.543307+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/spark_***.py', '--cfg-path', '/tmp/tmp6myh8i_p']
[2025-08-18T15:39:54.045+0000] {standard_task_runner.py:85} INFO - Job 53: Subtask python_job
[2025-08-18T15:39:54.109+0000] {task_command.py:415} INFO - Running <TaskInstance: sparking_flow.python_job manual__2025-08-18T15:39:50.543307+00:00 [running]> on host 81b7fe425a18
[2025-08-18T15:39:54.203+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Kudzaishe Manyanya' AIRFLOW_CTX_DAG_ID='sparking_flow' AIRFLOW_CTX_TASK_ID='python_job' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T15:39:50.543307+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T15:39:50.543307+00:00'
[2025-08-18T15:39:54.216+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2025-08-18T15:39:54.218+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --jars /opt/spark/external-jars/apache-spark-sql-connector.jar --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py
[2025-08-18T15:39:54.652+0000] {spark_submit.py:579} INFO - WARNING: Using incubator modules: jdk.incubator.vector
[2025-08-18T15:39:55.817+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:55 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-08-18T15:39:57.491+0000] {spark_submit.py:579} INFO - Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
[2025-08-18T15:39:57.496+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:57 INFO SparkContext: Running Spark version 4.0.0
[2025-08-18T15:39:57.497+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:57 INFO SparkContext: OS info Linux, 6.6.87.2-microsoft-standard-WSL2, amd64
[2025-08-18T15:39:57.497+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:57 INFO SparkContext: Java version 17.0.15
[2025-08-18T15:39:57.517+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:57 INFO ResourceUtils: ==============================================================
[2025-08-18T15:39:57.518+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:57 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-08-18T15:39:57.519+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:57 INFO ResourceUtils: ==============================================================
[2025-08-18T15:39:57.519+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:57 INFO SparkContext: Submitted application: PythonWordCount
[2025-08-18T15:39:57.538+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:57 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-08-18T15:39:57.540+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:57 INFO ResourceProfile: Limiting resource is cpu
[2025-08-18T15:39:57.541+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:57 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-08-18T15:39:57.577+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:57 INFO SecurityManager: Changing view acls to: ***
[2025-08-18T15:39:57.578+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:57 INFO SecurityManager: Changing modify acls to: ***
[2025-08-18T15:39:57.578+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:57 INFO SecurityManager: Changing view acls groups to: ***
[2025-08-18T15:39:57.579+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:57 INFO SecurityManager: Changing modify acls groups to: ***
[2025-08-18T15:39:57.580+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:57 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: *** groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY; RPC SSL disabled
[2025-08-18T15:39:57.779+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:57 INFO Utils: Successfully started service 'sparkDriver' on port 38129.
[2025-08-18T15:39:57.803+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:57 INFO SparkEnv: Registering MapOutputTracker
[2025-08-18T15:39:57.812+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:57 INFO SparkEnv: Registering BlockManagerMaster
[2025-08-18T15:39:57.826+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:57 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-08-18T15:39:57.827+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:57 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-08-18T15:39:57.829+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:57 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-08-18T15:39:57.852+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:57 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-77053397-bcec-4e72-8e60-6f2b7099ed22
[2025-08-18T15:39:57.872+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:57 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-08-18T15:39:57.986+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:57 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-08-18T15:39:58.041+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:58 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-08-18T15:39:58.072+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:58 INFO SparkContext: Added JAR file:///opt/spark/external-jars/apache-spark-sql-connector.jar at spark://81b7fe425a18:38129/jars/apache-spark-sql-connector.jar with timestamp 1755531597485
[2025-08-18T15:39:58.087+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:58 INFO SecurityManager: Changing view acls to: ***
[2025-08-18T15:39:58.088+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:58 INFO SecurityManager: Changing modify acls to: ***
[2025-08-18T15:39:58.088+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:58 INFO SecurityManager: Changing view acls groups to: ***
[2025-08-18T15:39:58.089+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:58 INFO SecurityManager: Changing modify acls groups to: ***
[2025-08-18T15:39:58.089+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:58 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: *** groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY; RPC SSL disabled
[2025-08-18T15:39:58.195+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:58 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-08-18T15:39:58.241+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:58 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.3:7077 after 23 ms (0 ms spent in bootstraps)
[2025-08-18T15:39:58.329+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:58 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250818153958-0007
[2025-08-18T15:39:58.336+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:58 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 38149.
[2025-08-18T15:39:58.337+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:58 INFO NettyBlockTransferService: Server created on 81b7fe425a18:38149
[2025-08-18T15:39:58.338+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:58 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-08-18T15:39:58.349+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:58 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 81b7fe425a18, 38149, None)
[2025-08-18T15:39:58.355+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:58 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250818153958-0007/0 on worker-20250818041359-172.18.0.5-40851 (172.18.0.5:40851) with 2 core(s)
[2025-08-18T15:39:58.355+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:58 INFO BlockManagerMasterEndpoint: Registering block manager 81b7fe425a18:38149 with 434.4 MiB RAM, BlockManagerId(driver, 81b7fe425a18, 38149, None)
[2025-08-18T15:39:58.356+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:58 INFO StandaloneSchedulerBackend: Granted executor ID app-20250818153958-0007/0 on hostPort 172.18.0.5:40851 with 2 core(s), 1024.0 MiB RAM
[2025-08-18T15:39:58.357+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:58 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 81b7fe425a18, 38149, None)
[2025-08-18T15:39:58.358+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:58 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 81b7fe425a18, 38149, None)
[2025-08-18T15:39:58.444+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:58 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250818153958-0007/0 is now RUNNING
[2025-08-18T15:39:58.463+0000] {spark_submit.py:579} INFO - 25/08/18 15:39:58 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-08-18T15:40:00.694+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2025-08-18T15:40:00.694+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
[2025-08-18T15:40:00.694+0000] {spark_submit.py:579} INFO - conn = connection.create_connection(
[2025-08-18T15:40:00.695+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
[2025-08-18T15:40:00.695+0000] {spark_submit.py:579} INFO - for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
[2025-08-18T15:40:00.695+0000] {spark_submit.py:579} INFO - File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
[2025-08-18T15:40:00.695+0000] {spark_submit.py:579} INFO - for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
[2025-08-18T15:40:00.696+0000] {spark_submit.py:579} INFO - socket.gaierror: [Errno -2] Name or service not known
[2025-08-18T15:40:00.696+0000] {spark_submit.py:579} INFO - 
[2025-08-18T15:40:00.696+0000] {spark_submit.py:579} INFO - During handling of the above exception, another exception occurred:
[2025-08-18T15:40:00.696+0000] {spark_submit.py:579} INFO - 
[2025-08-18T15:40:00.696+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2025-08-18T15:40:00.697+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
[2025-08-18T15:40:00.697+0000] {spark_submit.py:579} INFO - httplib_response = self._make_request(
[2025-08-18T15:40:00.697+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 403, in _make_request
[2025-08-18T15:40:00.697+0000] {spark_submit.py:579} INFO - self._validate_conn(conn)
[2025-08-18T15:40:00.697+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
[2025-08-18T15:40:00.698+0000] {spark_submit.py:579} INFO - conn.connect()
[2025-08-18T15:40:00.698+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
[2025-08-18T15:40:00.698+0000] {spark_submit.py:579} INFO - self.sock = conn = self._new_conn()
[2025-08-18T15:40:00.698+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
[2025-08-18T15:40:00.699+0000] {spark_submit.py:579} INFO - raise NewConnectionError(
[2025-08-18T15:40:00.699+0000] {spark_submit.py:579} INFO - urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x71b2a65c43d0>: Failed to establish a new connection: [Errno -2] Name or service not known
[2025-08-18T15:40:00.699+0000] {spark_submit.py:579} INFO - 
[2025-08-18T15:40:00.699+0000] {spark_submit.py:579} INFO - During handling of the above exception, another exception occurred:
[2025-08-18T15:40:00.700+0000] {spark_submit.py:579} INFO - 
[2025-08-18T15:40:00.700+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2025-08-18T15:40:00.700+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
[2025-08-18T15:40:00.700+0000] {spark_submit.py:579} INFO - resp = conn.urlopen(
[2025-08-18T15:40:00.701+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
[2025-08-18T15:40:00.702+0000] {spark_submit.py:579} INFO - retries = retries.increment(
[2025-08-18T15:40:00.702+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
[2025-08-18T15:40:00.702+0000] {spark_submit.py:579} INFO - raise MaxRetryError(_pool, url, error or ResponseError(cause))
[2025-08-18T15:40:00.703+0000] {spark_submit.py:579} INFO - urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.chess.com', port=443): Max retries exceeded with url: /pub/leaderboards (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x71b2a65c43d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-08-18T15:40:00.703+0000] {spark_submit.py:579} INFO - 
[2025-08-18T15:40:00.703+0000] {spark_submit.py:579} INFO - During handling of the above exception, another exception occurred:
[2025-08-18T15:40:00.704+0000] {spark_submit.py:579} INFO - 
[2025-08-18T15:40:00.704+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2025-08-18T15:40:00.704+0000] {spark_submit.py:579} INFO - File "/opt/***/jobs/python/wordcountjob.py", line 32, in <module>
[2025-08-18T15:40:00.704+0000] {spark_submit.py:579} INFO - response = requests.get(url, headers=headers)
[2025-08-18T15:40:00.705+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/api.py", line 73, in get
[2025-08-18T15:40:00.705+0000] {spark_submit.py:579} INFO - return request("get", url, params=params, **kwargs)
[2025-08-18T15:40:00.705+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
[2025-08-18T15:40:00.705+0000] {spark_submit.py:579} INFO - return session.request(method=method, url=url, **kwargs)
[2025-08-18T15:40:00.706+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
[2025-08-18T15:40:00.706+0000] {spark_submit.py:579} INFO - resp = self.send(prep, **send_kwargs)
[2025-08-18T15:40:00.707+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
[2025-08-18T15:40:00.707+0000] {spark_submit.py:579} INFO - r = adapter.send(request, **kwargs)
[2025-08-18T15:40:00.707+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
[2025-08-18T15:40:00.708+0000] {spark_submit.py:579} INFO - raise ConnectionError(e, request=request)
[2025-08-18T15:40:00.708+0000] {spark_submit.py:579} INFO - requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.chess.com', port=443): Max retries exceeded with url: /pub/leaderboards (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x71b2a65c43d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-08-18T15:40:00.757+0000] {spark_submit.py:579} INFO - 25/08/18 15:40:00 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.18.0.5:41674) with ID 0, ResourceProfileId 0
[2025-08-18T15:40:00.833+0000] {spark_submit.py:579} INFO - 25/08/18 15:40:00 INFO SparkContext: Invoking stop() from shutdown hook
[2025-08-18T15:40:00.838+0000] {spark_submit.py:579} INFO - 25/08/18 15:40:00 INFO SparkContext: SparkContext is stopping with exitCode 0 from run at Executors.java:539.
[2025-08-18T15:40:00.846+0000] {spark_submit.py:579} INFO - 25/08/18 15:40:00 INFO SparkUI: Stopped Spark web UI at http://81b7fe425a18:4040
[2025-08-18T15:40:00.849+0000] {spark_submit.py:579} INFO - 25/08/18 15:40:00 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-08-18T15:40:00.850+0000] {spark_submit.py:579} INFO - 25/08/18 15:40:00 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2025-08-18T15:40:00.866+0000] {spark_submit.py:579} INFO - 25/08/18 15:40:00 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-08-18T15:40:00.890+0000] {spark_submit.py:579} INFO - 25/08/18 15:40:00 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-08-18T15:40:00.891+0000] {spark_submit.py:579} INFO - 25/08/18 15:40:00 INFO MemoryStore: MemoryStore cleared
[2025-08-18T15:40:00.892+0000] {spark_submit.py:579} INFO - 25/08/18 15:40:00 INFO BlockManager: BlockManager stopped
[2025-08-18T15:40:00.897+0000] {spark_submit.py:579} INFO - 25/08/18 15:40:00 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-08-18T15:40:00.899+0000] {spark_submit.py:579} INFO - 25/08/18 15:40:00 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-08-18T15:40:00.915+0000] {spark_submit.py:579} INFO - 25/08/18 15:40:00 INFO SparkContext: Successfully stopped SparkContext
[2025-08-18T15:40:00.916+0000] {spark_submit.py:579} INFO - 25/08/18 15:40:00 INFO ShutdownHookManager: Shutdown hook called
[2025-08-18T15:40:00.917+0000] {spark_submit.py:579} INFO - 25/08/18 15:40:00 INFO ShutdownHookManager: Deleting directory /tmp/spark-570a8877-a43a-4707-8f0f-b7bc40bd8ae6
[2025-08-18T15:40:00.927+0000] {spark_submit.py:579} INFO - 25/08/18 15:40:00 INFO ShutdownHookManager: Deleting directory /tmp/spark-6b8a8a62-7900-41c7-9e67-8e74cfb852d7
[2025-08-18T15:40:00.939+0000] {spark_submit.py:579} INFO - 25/08/18 15:40:00 INFO ShutdownHookManager: Deleting directory /tmp/spark-6b8a8a62-7900-41c7-9e67-8e74cfb852d7/pyspark-b37cc55f-1234-4118-bd6d-b16b67ed5e8f
[2025-08-18T15:40:00.983+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --jars /opt/spark/external-jars/apache-spark-sql-connector.jar --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py. Error code is: 1.
[2025-08-18T15:40:00.987+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=sparking_flow, task_id=python_job, execution_date=20250818T153950, start_date=20250818T153954, end_date=20250818T154000
[2025-08-18T15:40:00.998+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 53 for task python_job (Cannot execute: spark-submit --master spark://spark-master:7077 --jars /opt/spark/external-jars/apache-spark-sql-connector.jar --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py. Error code is: 1.; 8326)
[2025-08-18T15:40:01.039+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-08-18T15:40:01.123+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
