[2025-08-18T14:00:03.900+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparking_flow.python_job scheduled__2025-08-18T12:00:00+00:00 [queued]>
[2025-08-18T14:00:03.907+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparking_flow.python_job scheduled__2025-08-18T12:00:00+00:00 [queued]>
[2025-08-18T14:00:03.907+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-08-18T14:00:03.918+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): python_job> on 2025-08-18 12:00:00+00:00
[2025-08-18T14:00:03.922+0000] {standard_task_runner.py:57} INFO - Started process 6983 to run task
[2025-08-18T14:00:03.925+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sparking_flow', 'python_job', 'scheduled__2025-08-18T12:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/spark_***.py', '--cfg-path', '/tmp/tmp94ikjo2t']
[2025-08-18T14:00:03.928+0000] {standard_task_runner.py:85} INFO - Job 49: Subtask python_job
[2025-08-18T14:00:03.987+0000] {task_command.py:415} INFO - Running <TaskInstance: sparking_flow.python_job scheduled__2025-08-18T12:00:00+00:00 [running]> on host 81b7fe425a18
[2025-08-18T14:00:04.069+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Kudzaishe Manyanya' AIRFLOW_CTX_DAG_ID='sparking_flow' AIRFLOW_CTX_TASK_ID='python_job' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-18T12:00:00+00:00'
[2025-08-18T14:00:04.082+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2025-08-18T14:00:04.083+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --jars /opt/spark/external-jars/apache-spark-sql-connector.jar --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py
[2025-08-18T14:00:04.873+0000] {spark_submit.py:579} INFO - WARNING: Using incubator modules: jdk.incubator.vector
[2025-08-18T14:00:06.400+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:06 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-08-18T14:00:08.769+0000] {spark_submit.py:579} INFO - Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
[2025-08-18T14:00:08.775+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:08 INFO SparkContext: Running Spark version 4.0.0
[2025-08-18T14:00:08.777+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:08 INFO SparkContext: OS info Linux, 6.6.87.2-microsoft-standard-WSL2, amd64
[2025-08-18T14:00:08.778+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:08 INFO SparkContext: Java version 17.0.15
[2025-08-18T14:00:08.801+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:08 INFO ResourceUtils: ==============================================================
[2025-08-18T14:00:08.802+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:08 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-08-18T14:00:08.802+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:08 INFO ResourceUtils: ==============================================================
[2025-08-18T14:00:08.803+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:08 INFO SparkContext: Submitted application: PythonWordCount
[2025-08-18T14:00:08.827+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:08 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-08-18T14:00:08.830+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:08 INFO ResourceProfile: Limiting resource is cpu
[2025-08-18T14:00:08.831+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:08 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-08-18T14:00:08.875+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:08 INFO SecurityManager: Changing view acls to: ***
[2025-08-18T14:00:08.877+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:08 INFO SecurityManager: Changing modify acls to: ***
[2025-08-18T14:00:08.878+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:08 INFO SecurityManager: Changing view acls groups to: ***
[2025-08-18T14:00:08.878+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:08 INFO SecurityManager: Changing modify acls groups to: ***
[2025-08-18T14:00:08.881+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:08 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: *** groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY; RPC SSL disabled
[2025-08-18T14:00:09.108+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:09 INFO Utils: Successfully started service 'sparkDriver' on port 41805.
[2025-08-18T14:00:09.136+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:09 INFO SparkEnv: Registering MapOutputTracker
[2025-08-18T14:00:09.146+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:09 INFO SparkEnv: Registering BlockManagerMaster
[2025-08-18T14:00:09.162+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:09 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-08-18T14:00:09.162+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:09 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-08-18T14:00:09.165+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:09 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-08-18T14:00:09.189+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:09 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-a42a4575-f02c-4628-badb-23ab2be83cfa
[2025-08-18T14:00:09.211+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:09 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-08-18T14:00:09.359+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:09 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-08-18T14:00:09.426+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:09 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-08-18T14:00:09.474+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:09 INFO SparkContext: Added JAR file:///opt/spark/external-jars/apache-spark-sql-connector.jar at spark://81b7fe425a18:41805/jars/apache-spark-sql-connector.jar with timestamp 1755525608761
[2025-08-18T14:00:09.495+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:09 INFO SecurityManager: Changing view acls to: ***
[2025-08-18T14:00:09.499+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:09 INFO SecurityManager: Changing modify acls to: ***
[2025-08-18T14:00:09.500+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:09 INFO SecurityManager: Changing view acls groups to: ***
[2025-08-18T14:00:09.500+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:09 INFO SecurityManager: Changing modify acls groups to: ***
[2025-08-18T14:00:09.501+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:09 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: *** groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY; RPC SSL disabled
[2025-08-18T14:00:09.722+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:09 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-08-18T14:00:09.781+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:09 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.3:7077 after 31 ms (0 ms spent in bootstraps)
[2025-08-18T14:00:10.170+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:10 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250818140010-0005
[2025-08-18T14:00:10.190+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:10 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 38939.
[2025-08-18T14:00:10.192+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:10 INFO NettyBlockTransferService: Server created on 81b7fe425a18:38939
[2025-08-18T14:00:10.197+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:10 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-08-18T14:00:10.244+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:10 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 81b7fe425a18, 38939, None)
[2025-08-18T14:00:10.254+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:10 INFO BlockManagerMasterEndpoint: Registering block manager 81b7fe425a18:38939 with 434.4 MiB RAM, BlockManagerId(driver, 81b7fe425a18, 38939, None)
[2025-08-18T14:00:10.258+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:10 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 81b7fe425a18, 38939, None)
[2025-08-18T14:00:10.261+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:10 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 81b7fe425a18, 38939, None)
[2025-08-18T14:00:10.277+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:10 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250818140010-0005/0 on worker-20250818041359-172.18.0.5-40851 (172.18.0.5:40851) with 2 core(s)
[2025-08-18T14:00:10.279+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:10 INFO StandaloneSchedulerBackend: Granted executor ID app-20250818140010-0005/0 on hostPort 172.18.0.5:40851 with 2 core(s), 1024.0 MiB RAM
[2025-08-18T14:00:10.474+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:10 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-08-18T14:00:10.769+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:10 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250818140010-0005/0 is now RUNNING
[2025-08-18T14:00:13.254+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2025-08-18T14:00:13.257+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
[2025-08-18T14:00:13.258+0000] {spark_submit.py:579} INFO - conn = connection.create_connection(
[2025-08-18T14:00:13.258+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
[2025-08-18T14:00:13.258+0000] {spark_submit.py:579} INFO - for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
[2025-08-18T14:00:13.259+0000] {spark_submit.py:579} INFO - File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
[2025-08-18T14:00:13.259+0000] {spark_submit.py:579} INFO - for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
[2025-08-18T14:00:13.260+0000] {spark_submit.py:579} INFO - socket.gaierror: [Errno -2] Name or service not known
[2025-08-18T14:00:13.260+0000] {spark_submit.py:579} INFO - 
[2025-08-18T14:00:13.260+0000] {spark_submit.py:579} INFO - During handling of the above exception, another exception occurred:
[2025-08-18T14:00:13.261+0000] {spark_submit.py:579} INFO - 
[2025-08-18T14:00:13.261+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2025-08-18T14:00:13.262+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
[2025-08-18T14:00:13.262+0000] {spark_submit.py:579} INFO - httplib_response = self._make_request(
[2025-08-18T14:00:13.263+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 403, in _make_request
[2025-08-18T14:00:13.263+0000] {spark_submit.py:579} INFO - self._validate_conn(conn)
[2025-08-18T14:00:13.264+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
[2025-08-18T14:00:13.264+0000] {spark_submit.py:579} INFO - conn.connect()
[2025-08-18T14:00:13.265+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
[2025-08-18T14:00:13.266+0000] {spark_submit.py:579} INFO - self.sock = conn = self._new_conn()
[2025-08-18T14:00:13.266+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
[2025-08-18T14:00:13.267+0000] {spark_submit.py:579} INFO - raise NewConnectionError(
[2025-08-18T14:00:13.267+0000] {spark_submit.py:579} INFO - urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x780d025d06d0>: Failed to establish a new connection: [Errno -2] Name or service not known
[2025-08-18T14:00:13.268+0000] {spark_submit.py:579} INFO - 
[2025-08-18T14:00:13.268+0000] {spark_submit.py:579} INFO - During handling of the above exception, another exception occurred:
[2025-08-18T14:00:13.268+0000] {spark_submit.py:579} INFO - 
[2025-08-18T14:00:13.269+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2025-08-18T14:00:13.269+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
[2025-08-18T14:00:13.269+0000] {spark_submit.py:579} INFO - resp = conn.urlopen(
[2025-08-18T14:00:13.270+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
[2025-08-18T14:00:13.270+0000] {spark_submit.py:579} INFO - retries = retries.increment(
[2025-08-18T14:00:13.271+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
[2025-08-18T14:00:13.271+0000] {spark_submit.py:579} INFO - raise MaxRetryError(_pool, url, error or ResponseError(cause))
[2025-08-18T14:00:13.272+0000] {spark_submit.py:579} INFO - urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.chess.com', port=443): Max retries exceeded with url: /pub/leaderboards (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x780d025d06d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-08-18T14:00:13.273+0000] {spark_submit.py:579} INFO - 
[2025-08-18T14:00:13.273+0000] {spark_submit.py:579} INFO - During handling of the above exception, another exception occurred:
[2025-08-18T14:00:13.274+0000] {spark_submit.py:579} INFO - 
[2025-08-18T14:00:13.274+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2025-08-18T14:00:13.275+0000] {spark_submit.py:579} INFO - File "/opt/***/jobs/python/wordcountjob.py", line 32, in <module>
[2025-08-18T14:00:13.275+0000] {spark_submit.py:579} INFO - response = requests.get(url, headers=headers)
[2025-08-18T14:00:13.276+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/api.py", line 73, in get
[2025-08-18T14:00:13.276+0000] {spark_submit.py:579} INFO - return request("get", url, params=params, **kwargs)
[2025-08-18T14:00:13.276+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
[2025-08-18T14:00:13.277+0000] {spark_submit.py:579} INFO - return session.request(method=method, url=url, **kwargs)
[2025-08-18T14:00:13.278+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
[2025-08-18T14:00:13.278+0000] {spark_submit.py:579} INFO - resp = self.send(prep, **send_kwargs)
[2025-08-18T14:00:13.278+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
[2025-08-18T14:00:13.279+0000] {spark_submit.py:579} INFO - r = adapter.send(request, **kwargs)
[2025-08-18T14:00:13.279+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
[2025-08-18T14:00:13.280+0000] {spark_submit.py:579} INFO - raise ConnectionError(e, request=request)
[2025-08-18T14:00:13.280+0000] {spark_submit.py:579} INFO - requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.chess.com', port=443): Max retries exceeded with url: /pub/leaderboards (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x780d025d06d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-08-18T14:00:13.494+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:13 INFO SparkContext: Invoking stop() from shutdown hook
[2025-08-18T14:00:13.504+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:13 INFO SparkContext: SparkContext is stopping with exitCode 0 from run at Executors.java:539.
[2025-08-18T14:00:13.543+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:13 INFO SparkUI: Stopped Spark web UI at http://81b7fe425a18:4040
[2025-08-18T14:00:13.560+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:13 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-08-18T14:00:13.564+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:13 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2025-08-18T14:00:13.602+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:13 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-08-18T14:00:13.669+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:13 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-08-18T14:00:13.671+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:13 INFO MemoryStore: MemoryStore cleared
[2025-08-18T14:00:13.672+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:13 INFO BlockManager: BlockManager stopped
[2025-08-18T14:00:13.681+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:13 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-08-18T14:00:13.684+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:13 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-08-18T14:00:13.712+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:13 INFO SparkContext: Successfully stopped SparkContext
[2025-08-18T14:00:13.714+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:13 INFO ShutdownHookManager: Shutdown hook called
[2025-08-18T14:00:13.715+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:13 INFO ShutdownHookManager: Deleting directory /tmp/spark-e53506d9-db8e-486e-84cf-f04abbffa9c0
[2025-08-18T14:00:13.736+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:13 INFO ShutdownHookManager: Deleting directory /tmp/spark-0dac2dd3-42f6-4bb3-bda5-05c1d3d7a7f3
[2025-08-18T14:00:13.753+0000] {spark_submit.py:579} INFO - 25/08/18 14:00:13 INFO ShutdownHookManager: Deleting directory /tmp/spark-0dac2dd3-42f6-4bb3-bda5-05c1d3d7a7f3/pyspark-c75a8a9c-9022-4e50-8f4c-f6eaa42abf4a
[2025-08-18T14:00:13.939+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --jars /opt/spark/external-jars/apache-spark-sql-connector.jar --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py. Error code is: 1.
[2025-08-18T14:00:13.962+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=sparking_flow, task_id=python_job, execution_date=20250818T120000, start_date=20250818T140003, end_date=20250818T140013
[2025-08-18T14:00:14.014+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 49 for task python_job (Cannot execute: spark-submit --master spark://spark-master:7077 --jars /opt/spark/external-jars/apache-spark-sql-connector.jar --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py. Error code is: 1.; 6983)
[2025-08-18T14:00:14.105+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-08-18T14:00:14.159+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
